liquibase:
  enabled: false
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    test-connection: true
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
    
  